### PR TITLE
chore: use `rustfmt` to fmt the code style

### PR DESCRIPTION
**Pull request by qianxi0410**
This pr does not provide features, but unifies the code format.
In fact, formatting tools are provided in the rust tool chain, we just need to run `cargo fmt` in the working directory. 

If you use VS Code, I recommend you to add this in your settings file:

```json
  "[rust]": {
    "editor.defaultFormatter": "rust-lang.rust-analyzer",
    "editor.formatOnSave": true
  },
```
if you're not to install the fmt tool, just run command:

```bash
rustup component add rustfmt
```

### CODE REVIEW

**Comment by hsluoyz** [comment]
@qianxi0410 @leavelet which identation is better? Tab or spaces?

**Comment by hsluoyz** [comment]
@qianxi0410 @leavelet which identation is better? Tab or spaces?

**Comment by qianxi0410** [comment]
@leavelet Thanks for such detailed advice.
The default is the best.
In that case, I would suggest using the default `rustfmt` configuration, we no longer need `rustfmt.toml` and I will remove it.

**Comment by hsluoyz** [comment]
@leavelet plz review

**Comment by leavelet** [comment]
I think it's ok

**Pull request merged**
